### ISSUE TITLE
3D skeleton from point cloud

### ISSUE THREAD

**Issue by TalBarami** [MasterHow/EventPointPose#3]
Hello, and thanks for publishing your code & models.
I wondered if this method is suitable for extracting the skeletal representation of a single 3D human point cloud rather than a series of 3D human point clouds.

**Comment by bestchen97** [comment]
Hi! Thanks for your attention. The 3D point cloud in our work is obtained from event cameras, where the third dimension is _t_, rather than _z_. Extracting 3D skeletons from a single view of event point cloud will lead to future work, which falls into the category of single-view approaches for human pose estimation.
