### ISSUE TITLE
Function 'nanmean' (input argument of type 'single') is undefined.

### ISSUE THREAD

**Issue by takeyamayuki** [MasterHow/EventPointPose#4]
Hi, thank you for the great project.

I followed the README for `EventPointPose` and while running `Generate_DHP19_pointcloud_all_mean.m` I got the following error.

```
Function 'nanmean' (input argument of type 'single') is undefined.

Error: GetPoseLabels (line 4)
    pose(1,:) = nanmean(XYZPOS.XYZPOS.head(last_k:k,:),1);

Error: Generate_DHP19_pointcloud_all_mean (line 260)
                    pose = GetPoseLabels(XYZPOS, last_k, k, is_MeanLabel);

4       pose(1,:) = nanmean(XYZPOS.XYZPOS.head(last_k:k,:),1);
```

my environment: Windows 11, MATLAB R2022a

How should I deal with this issue?
Thank you in advance.

**Comment by bestchen97** [comment]
Hi, thank you for the interest.

I guess it might be caused by the version of MATLAB. You could try to change all `nanmean` function with `mean` following  this [doc](https://www.mathworks.com/help/matlab/ref/mean.html#d124e934248), such as `pose(1,:) = mean(XYZPOS.XYZPOS.head(last_k:k,:),1,'omitnan');` 

Let me know whether it could help you with this error.

**Comment by takeyamayuki** [comment]
Thank you for your prompt response.
I made the edits as suggested and it worked fine.

I have sent a pull request with the suggested changes and a fix for an error that the `models` file was not being read when running `python evaluate/evaluate.py` to evaluate it.

I would appreciate it if you could merge them if you like.
